# Generated by Django 4.2.2 on 2023-07-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(default='img/user-icon.png', upload_to='user/'),
        ),
    ]
