# Generated by Django 4.2.2 on 2023-07-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(default='/static/img/user-icon.png', upload_to='user/'),
        ),
    ]
